### ISSUE TITLE
Regression: Can't use virtual loop variable as macro call parameter anymore

### ISSUE THREAD

**Issue by seijikun** [rinja-rs/rinja#564]
**Describe the bug**
Introduced in commit 693f86d1c44876ddf037b864db6350ea754262f0, there is a regression that causes the use of `loop.<xx>` as a macro invocation argument to fail.

**To Reproduce:**
```jinja
{% macro column(idx) %}
    {{ idx }}
{% endmacro %}

{% macro nested_arr(arr) %}
    {% for e in arr %}
        {{ loop.index0 }}  {# works without problem #}
        {{ column(loop.index0) }}   {# fails to build #}
    {% endfor %}
{% endmacro %}

{{ nested_arr([1, 2, 3]) }}
```

**The error:**

```
error[E0425]: cannot find value `__askama_item` in this scope
  --> src/main.rs:49:10
   |
49 | #[derive(Template)]
   |          ^^^^^^^^ not found in this scope
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by seijikun** [comment]
I am having a hard time getting to the bottom of it.
`cargo expand` shows the following generated code for my minimal reproducer:

```rust
use askama::Template;
struct IndexPage {}
#[allow(
    clippy::init_numbered_fields,
    non_shorthand_field_patterns,
    clippy::suspicious_else_formatting,
    dead_code,
    non_camel_case_types,
    non_snake_case,
)]
const _: () = {
    extern crate askama;
    #[automatically_derived]
    impl askama::Template for IndexPage {
        fn render_into_with_values<AskamaW>(
            &self,
            __askama_writer: &mut AskamaW,
            __askama_values: &dyn askama::Values,
        ) -> askama::Result<()>
        where
            AskamaW: askama::helpers::core::fmt::Write
                + ?askama::helpers::core::marker::Sized,
        {
            #[allow(unused_imports)]
            use askama::{
                filters::{AutoEscape as _, WriteWritable as _},
                helpers::{ResultConverter as _, core::fmt::Write as _},
            };
            const _: &[askama::helpers::core::primitive::u8] = b"{# {{ test() | noargs | safe }}\n\n{{ test() | req1(\"lol\") | safe }}\n\n{{ test() | opt1 | safe }}\n{{ test() | opt1(\"nodefault\") | safe }}\n{{ test() | opt1(opt0 = \"nodefault\") | safe }}\n\n{{ test() | req1_opt1(\"req\") | safe }}\n{{ test() | req1_opt1(\"req\", \"supplied\") | safe }}\n{{ test() | req1_opt1(\"req\", opt0 = \"supplied\") | safe }}\n\n{{ test() | shared_generic(\"blub\") | safe }}\n\n{{ test() | noargs(\"lol\") }} #}\n\n{% macro column(idx) %}\n\t{{ idx }}\n{% endmacro %}\n\n{% macro nested_arr(arr) %}\n\t{% for e in arr %}\n        {{ column(loop.index0) }}\n\t{% endfor %}\n{% endmacro %}\n\n{{ nested_arr([1, 2, 3]) }}";
            {
                let arr = &([1, 2, 3]);
                let __askama_iter = (arr).into_iter();
                for (e, __askama_item) in askama::helpers::TemplateLoop::new(
                    __askama_iter,
                ) {
                    {
                        match (
                            &((&&askama::filters::AutoEscaper::new(
                                &(__askama_item.index0),
                                askama::filters::Html,
                            ))
                                .askama_auto_escape()?),
                        ) {
                            (__askama_expr1,) => {
                                (&&&askama::filters::Writable(__askama_expr1))
                                    .askama_write(__askama_writer, __askama_values)?;
                            }
                        }
                    }
                }
            }
            askama::Result::Ok(())
        }
        const SIZE_HINT: askama::helpers::core::primitive::usize = 15usize;
    }
    /// Implement the [`format!()`][askama::helpers::std::format] trait for [`IndexPage`]
    ///
    /// Please be aware of the rendering performance notice in the [`Template`][askama::Template] trait.
    #[automatically_derived]
    impl askama::helpers::core::fmt::Display for IndexPage {
        #[inline]
        fn fmt(
            &self,
            f: &mut askama::helpers::core::fmt::Formatter<'_>,
        ) -> askama::helpers::core::fmt::Result {
            askama::Template::render_into(self, f)
                .map_err(|_| askama::helpers::core::fmt::Error)
        }
    }
    #[automatically_derived]
    impl askama::FastWritable for IndexPage {
        #[inline]
        fn write_into<AskamaW>(
            &self,
            dest: &mut AskamaW,
            values: &dyn askama::Values,
        ) -> askama::Result<()>
        where
            AskamaW: askama::helpers::core::fmt::Write
                + ?askama::helpers::core::marker::Sized,
        {
            askama::Template::render_into_with_values(self, dest, values)
        }
    }
};
pub fn main() {
    println!("{}", IndexPage {}.render().unwrap());
}
```

When I pasted that into my `main.rs` and run it - it works as expected. 👀

**Comment by GuillaumeGomez** [comment]
Minimized case:

```rust
use askama::Template;

macro_rules! looper {
    ($l:literal) => {
    #[derive(Template)]
    #[template(
        source = $l,
        ext = "txt",
        //print = "code"
    )]
    pub struct X;
    }
}

looper!(r#"
{% macro column(idx) %}
    {{ idx }}
{% endmacro %}

{% macro nested_arr(arr) %}
    {% for e in arr %}
        {{ loop.index0 }}  {# works without problem #}
        {{ column(loop.index0) }}   {# fails to build #}
    {% endfor %}
{% endmacro %}

{{ nested_arr([1, 2, 3]) }}"#);

fn main() {
    println!("{}", X.render().unwrap());
}
```
